Trong xây dựng một mô hình SVM, việc lựa chọn kernel thích hợp và việc điềuchỉnh để có được tham số thích hợp cho kernel đó là yếu tố vô cùng quan trọng. 
\cite{hsu2003practical} đưa ra một quy trình để có thể đạt được kết quả chấp nhận được đối với hầu hết tất cả mọi trường hợp. Quy trình đó như sau:

\begin{itemize}
  \item Biến đổi số liệu phù hợp với gói ứng dụng SVM
  \item Thực hiện chuẩn hoá bộ số liệu
  \item Sử dụng kernel RBF $K(x, y) = e^{-\gamma{\|x - y\|}^2}$
\end{itemize}



